### ISSUE TITLE
Error after 1.57b Import

### ISSUE THREAD

**Issue by Hawkadium** [suriyun-production/mmorpg-kit-docs#544]
Getting the error below, after updating to 1.57b.  Tried all the usual fixes, restarting, etc.
**Unity 2019.4.5f1**

_Assets\UnityMultiplayerARPG\Core\Scripts\UI\Item\UIBaseCharacterItemByIndex.cs(7,70): error CS0246: The type or namespace name 'UICharacterItemByIndexData' could not be found (are you missing a using directive or an assembly reference?)_

**Comment by insthync** [comment]
You can remove `UIBaseCharacterItemByIndex.cs`, It's actually renamed to `UIBaseOwningCharacterItem`

**Comment by Hawkadium** [comment]
Beautiful. Working now.
