### ISSUE TITLE
[BUG] error "The type 'IAsyncDisposable' exists in both" when update to 1.81h2 (2023-03-31) version

### ISSUE THREAD

**Issue by Wolfcrin** [suriyun-production/mmorpg-kit-docs#1979]
Hello i have this error after to update the proyecto version to 1.81h2

Unity Version: 2021.3.20f1

ERRORs:
_Assets\UnityMultiplayerARPG\Core\LiteNetLibManager\Plugins\ZLogger\AsyncStreamLineMessageWriter.cs(12,69): error CS0433: The type 'IAsyncDisposable' exists in both 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'_

_Assets\UnityMultiplayerARPG\Core\LiteNetLibManager\Plugins\ZLogger\IAsyncLogProcessor.cs(7,43): error CS0433: The type 'IAsyncDisposable' exists in both 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'_

![image](https://user-images.githubusercontent.com/31020476/229249984-ef69bf9c-fc8f-4462-a6c1-847082744f8b.png)

**Comment by insthync** [comment]
Try do this: https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/151-working-with-2021

**Comment by Wolfcrin** [comment]
Yes, It works. Thank you.

I had also forgotten to install the packge
MMORPG_KIT2021.2_Microsoft.Bcl.AsyncInterfaces5.0.0.dll.unitypackage


Close
