### ISSUE TITLE
Error RewardExp

### ISSUE THREAD

**Issue by brabaris** [suriyun-production/mmorpg-kit-docs#690]
Hello! After upgrading to 1.61, there is an error in the RewardPvp plugin. Related to file changes:
BaseGameplayRule.cs, DefaultGameplayRule.cs, BaseCharacterEntity.cs. (out int rewardedExp).

Assets\GameData\Scripts\PvpRewards.cs(76,53): error CS7036: There is no argument given that corresponds to the required formal parameter 'rewardedExp' of 'BaseGameplayRule.RewardExp(BaseCharacterEntity, Reward, float, RewardGivenType, out int)'

`using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace MultiplayerARPG
{
public partial class BasePlayerCharacterEntity
{
[Header("Killing Rewards:")]
[SerializeField]
private int rewardGoldMin;
[SerializeField]
private int rewardGoldMax;
[SerializeField]
private int rewardExpMin;
[SerializeField]
private int rewardExpMax;

    public virtual int RewardGold()
    {
        int min = rewardGoldMin;
        int max = rewardGoldMax;
        if (min > max)
            min = max;
        return Random.Range(min, max);
    }
    public virtual int RewardExp()
    {
        int min = rewardExpMin;
        int max = rewardExpMax;
        if (min > max)
            min = max;
        return Random.Range(min, max);
    }

    [DevExtMethods("Awake")]
    public void Awake_PvpGetGold()
    {
        onReceivedDamage += ReceivedDamage_PvpGetGold;
    }

    [DevExtMethods("OnDestroy")]
    public void OnDestroy_PvpGetGold()
    {
        onReceivedDamage -= ReceivedDamage_PvpGetGold;
    }

    private void ReceivedDamage_PvpGetGold(
        Vector3 fromPosition,
        IGameEntity attacker,
        CombatAmountType combatAmountType,
        int damage,
        CharacterItem weapon,
        BaseSkill skill,
        short skillLevel)
    {
        if (!IsServer)
            return;

        if (attacker == null || !(attacker.Entity is BasePlayerCharacterEntity))
            return;

        int rewardGold = RewardGold();
        int rewardExp = RewardExp();

        BasePlayerCharacterEntity character = (attacker.Entity as BasePlayerCharacterEntity);
        if (!this.IsDead())
            return;

        character.Gold += rewardGold;
        CurrentGameManager.SendNotifyRewardGold(character.ConnectionId, rewardGold);

        character.Exp += rewardExp;
        CurrentGameManager.SendNotifyRewardExp(character.ConnectionId, rewardExp);

        if (GameInstance.Singleton.GameplayRule.RewardExp(character, new Reward()
            {
            }, 1f, RewardGivenType.None))
        {
            character.CallAllOnLevelUp();
        }
         
    }
}

}`

**Comment by insthync** [comment]
You just have to add a parameter in `RewardExp` function, the error message told what is missing.
