### ISSUE TITLE
Can not build in WebGL

### ISSUE THREAD

**Issue by Reinhartdelille** [suriyun-production/mmorpg-kit-docs#2697]
**Describe the bug**
Hi, 

Quite experienced in Devops but I cant seem to get the latest MMOKit version to build to webGL. 

Though the code compiles under Visual Studio, whenever I try to build the addressables or other the client by itself, it throws the following error.

`Assets\UnityMultiplayerARPG\Core\LiteNetLibManager\Scripts\Transports\WebSocket\WebSocketClient.cs(105,55): error CS0246: The type or namespace name 'WebSocketSharp' could not be found (are you missing a using directive or an assembly reference?)`

Now if I read the code correct, in a pure webgl client circumstance the JS Lib should be taken and not the websocketSharp Project?  The dll is excluded when compiling to WebGL, and I believe the websocketsharp is only to be used serverside.

This is driven by the compiler directive #if UNITY_WEBGL && !UNITY_EDITOR

In this case I suspect it should fall back to what is in the JSLIB definition but it's not working.

Could this be something with the new version and that's not fixed yet? 

Can you give some guidance on how to setup the compile for WebGL?

**Comment by Reinhartdelille** [comment]
Btw using latest MMOKit and Unity 6000. Setting everything up as addressables

**Comment by Eniotnacram** [comment]
> Btw using latest MMOKit and Unity 6000. Setting everything up as addressables

Sorry for your issue, but I myself try to implement everything with addressable, but as no documentation is provided on this, I got a couple of questions. Would you mind adding me on discord to talk about it a lil? User: influency

**Comment by reidsneo** [comment]
![Image](https://github.com/user-attachments/assets/00f36dc1-2c3c-4521-93a6-f079250f41a8)

I think this is not addressable specific issue, last working good WebGL that I previously working on was 1.89
Currently on 1.92b is confirmed error (using Unity 6000.0.32f1)

**Comment by insthync** [comment]
https://github.com/insthync/LiteNetLibManager/commit/0a8bb861f4e48e63d842ecac13ae451bb1fa46d6

**Comment by reidsneo** [comment]
thanks the fix is working good!

**Comment by Reinhartdelille** [comment]
> > Btw using latest MMOKit and Unity 6000. Setting everything up as addressables
> 
> Sorry for your issue, but I myself try to implement everything with addressable, but as no documentation is provided on this, I got a couple of questions. Would you mind adding me on discord to talk about it a lil? User: influency

Sure no problem, i will add you as friend.
